# Generated by Django 6.0.3 on 2026-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, help_text='Display this category on the homepage.'),
        ),
    ]
