# Generated by Django 6.0.3 on 2026-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_display_order_category_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
    ]
