# Generated by Django 6.0.3 on 2026-03-24 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in KES')),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Our internal transaction reference.', max_length=200)),
                ('provider_ref', models.CharField(blank=True, help_text="Provider's reference (e.g. M-Pesa CheckoutRequestID, Stripe PaymentIntent ID).", max_length=200)),
                ('provider_response', models.JSONField(default=dict, help_text='Raw callback/webhook data from the payment provider.')),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, help_text='M-Pesa transaction receipt number from Safaricom.', max_length=100)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'), models.Index(fields=['method', 'status'], name='payments_method_5d17d7_idx')],
            },
        ),
    ]
