# Generated by Django 6.0.3 on 2026-03-24 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase Order'), ('sale', 'Sale'), ('return', 'Customer Return'), ('adjustment', 'Manual Adjustment'), ('reserved', 'Order Reserved'), ('released', 'Reservation Released')], db_index=True, max_length=20)),
                ('delta', models.IntegerField(help_text='+N = stock added, -N = stock removed')),
                ('quantity_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Order number, purchase order ref, etc.', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Units held by pending/confirmed orders.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when available stock drops to or below this number.')),
                ('track_inventory', models.BooleanField(default=True, help_text='If False, product is treated as always in stock.')),
                ('allow_backorder', models.BooleanField(default=False, help_text='Allow orders even when out of stock.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
    ]
