# Generated by Django 6.0.3 on 2026-03-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', '-viewed_at'], name='product_vie_product_e08eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['-viewed_at'], name='product_vie_viewed__5f815b_idx'),
        ),
    ]
